"""Initial migration.

Revision ID: 61eb8518f707
Revises: 
Create Date: 2024-01-30 17:40:36.158596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61eb8518f707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
