"""done

Revision ID: e7510a4db29a
Revises: 61eb8518f707
Create Date: 2024-01-30 17:42:42.573000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7510a4db29a'
down_revision = '61eb8518f707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
